---
name: Cachix Push

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

jobs:
  cache:
    uses: EricCrosson/nix-action/.github/workflows/cache.yml@v1
    with:
      cache: ericcrosson
    secrets:
      cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
